using System;
using System.Collections.Generic;
using UnityEditor;
using UnityEngine;
using System.IO;
using System.Security.Cryptography;
using System.Text;

namespace ScratchFramework
{
    public static class ScratchUtils_Editor
    {
        [MenuItem("Assets/Scratch/Convert TemplateDatas", false, 80)]
        public static void Editor_Convert_Datas()
        {
            if (Selection.gameObjects == null) return;

            var dataDicts = ScratchUtils.ConvertSimpleBlock(Selection.gameObjects);
            foreach (var dataDict in dataDicts)
            {
                string path = Path.Combine(ScratchConfig.Instance.TemplateDatasPath, dataDict.Key);
                File.WriteAllBytes($"{path}.bytes", dataDict.Value);
            }

            AssetDatabase.Refresh();

            var datas = AssetDatabase.FindAssets("t:TextAsset", new[] { ScratchConfig.Instance.TemplateDatasPath });

            ScratchConfig.Instance.TemplateDatas.Clear();
            StringBuilder sb = new StringBuilder();
            sb.AppendLine("//------------------------------------------------------------------------------\r\n" +
                          "// <auto-generated>\r\n" +
                          "//     This code was generated by a tool.\r\n" +
                          "//     Changes to this file may cause incorrect behavior and will be lost if\r\n" +
                          "//     the code is regenerated.\r\n" +
                          "// </auto-generated>\r\n" +
                          "//------------------------------------------------------------------------------");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using UnityEngine;");

            sb.AppendLine("namespace ScratchFramework");
            sb.AppendLine("{");


            List<BlockData> blockDatas = new List<BlockData>();
            for (int i = 0; i < datas.Length; i++)
            {
                string path = AssetDatabase.GUIDToAssetPath(datas[i]);

                TextAsset textAsset = AssetDatabase.LoadAssetAtPath<TextAsset>(path);
                if (textAsset != null)
                {
                    Block block = ScratchUtils.DeserializeBlock(textAsset.bytes);
                    ScratchConfig.Instance.TemplateDatas.Add(textAsset);
                    blockDatas.Add(block.GetDataRef() as BlockData);
                    GameObject.DestroyImmediate(block.gameObject);
                }
            }


            sb.AppendLine("\tpublic static class EngineBlockCodeExtension");
            sb.AppendLine("\t{");

            AddSummary("BlockData Template Dict", ref sb);
            sb.AppendLine("\t\tpublic static Dictionary<int, int> TemplateDict = new Dictionary<int, int>()");
            sb.AppendLine("\t\t{");
            for (int i = 0; i < blockDatas.Count; i++)
            {
                sb.Append("\t\t\t{(int)ScratchBlockType.");
                sb.Append($"{blockDatas[i].ScratchType}, {i}");
                sb.Append("},\r\n");
            }

            sb.AppendLine("\t\t};");

            AddSummary("BlockData Logic", ref sb);
            sb.AppendLine("\t\tpublic static IEngineBlockBaseData CreateBlockData(this ScratchBlockType type)");
            sb.AppendLine("\t\t{");
            sb.AppendLine("\t\t\tswitch (type)");
            sb.AppendLine("\t\t\t{");
            for (int i = 0; i < blockDatas.Count; i++)
            {
                sb.AppendLine("\t\t\t\tcase ScratchBlockType." + blockDatas[i].ScratchType + ": return new BlockLogic_" + blockDatas[i].ScratchType + "();");
            }

            sb.AppendLine("\t\t\t}");
            sb.AppendLine("\t\t\t return null;");
            sb.AppendLine("\t\t}");
            sb.AppendLine("\t}");

            ScratchBlockClass(ref sb, blockDatas);

            sb.AppendLine("}");
            ExportConfigTableCS(ScratchConfig.Instance.CsSharpPath + $"/EngineBlockCode.cs", sb);

            AssetDatabase.Refresh();
        }


        private static string GetInterfaceName(BlockType type)
        {
            string name = string.Empty;
            switch (type)
            {
                case BlockType.none:
                    break;
                case BlockType.Trigger:
                    return " : " + nameof(IEngineBlockTriggerBase);
                    break;
                case BlockType.Simple:
                    return " : " + nameof(IEngineBlockSimpleBase);
                    break;
                case BlockType.Condition:
                    return " : " + nameof(IEngineBlockConditionBase);
                    break;
                case BlockType.Loop:
                    return " : " + nameof(IEngineBlockLoopBase);
                    break;
                case BlockType.Operation:
                    return " : " + nameof(IEngineBlockOperationBase);
                    break;
                case BlockType.Define:
                    break;
                default:
                    throw new ArgumentOutOfRangeException(nameof(type), type, null);
            }

            return name;
        }

        private static void GetInputValuesLen(BlockData blockData, ref List<ScratchValueType> inputs, ref List<ScratchValueType> returns)
        {
            inputs.Clear();
            returns.Clear();

            for (int i = 0; i < blockData.SectionTreeList.Length; i++)
            {
                for (int j = 0; j < blockData.SectionTreeList[i].BlockHeadTreeList.Length; j++)
                {
                    var headData = blockData.SectionTreeList[i].BlockHeadTreeList[j];
                    DataType type = headData.DataType;
                    switch (type)
                    {
                        case DataType.Undefined:
                            break;
                        case DataType.Label:
                            break;
                        case DataType.Input:
                            break;
                        case DataType.Operation:
                            BlockHeaderParam_Data_Operation headOperationData = headData as BlockHeaderParam_Data_Operation;
                            returns.Add(headOperationData.ValueType);
                            break;
                        case DataType.VariableLabel:
                            break;
                        case DataType.RenturnVariableLabel:
                            break;
                        case DataType.Icon:
                            break;
                        default:
                            throw new ArgumentOutOfRangeException();
                    }
                }
            }
        }

        private static void GetInterfaceProperty(ref StringBuilder stringBuilder, BlockType type)
        {
            Type engineBlockType = null;
            switch (type)
            {
                case BlockType.none:
                    break;
                case BlockType.Trigger:
                    engineBlockType = typeof(IEngineBlockTriggerBase);
                    break;
                case BlockType.Simple:
                    engineBlockType = typeof(IEngineBlockSimpleBase);
                    break;
                case BlockType.Condition:
                    engineBlockType = typeof(IEngineBlockConditionBase);
                    break;
                case BlockType.Loop:
                    engineBlockType = typeof(IEngineBlockLoopBase);
                    break;
                case BlockType.Operation:
                    engineBlockType = typeof(IEngineBlockOperationBase);
                    break;
                case BlockType.Define:
                    break;
                default:
                    throw new ArgumentOutOfRangeException(nameof(type), type, null);
            }

            if (engineBlockType == null) return;

            var properties = engineBlockType.GetProperties();
            for (int i = 0; i < properties.Length; i++)
            {
                stringBuilder.AppendLine($"\t\tprivate {properties[i].PropertyType.Name} m_{properties[i].Name} = -1;");
                stringBuilder.AppendLine($"\t\tpublic {properties[i].PropertyType.Name} {properties[i].Name}");
                stringBuilder.AppendLine("\t\t{");
                stringBuilder.AppendLine($"\t\t\tget => m_{properties[i].Name};");
                if (properties[i].SetMethod != null)
                {
                    stringBuilder.AppendLine("\t\t\tset");
                    stringBuilder.AppendLine("\t\t\t{");
                    stringBuilder.AppendLine($"\t\t\tSet{properties[i].Name}(ref value);");
                    stringBuilder.AppendLine($"\t\t\tm_{properties[i].Name} = value;");
                    stringBuilder.AppendLine("\t\t\t}");
                }

                stringBuilder.AppendLine("\t\t}");
                stringBuilder.AppendLine($"\t\tpartial void Set{properties[i].Name}(ref {properties[i].PropertyType.Name} newData);");
            }

            return;
        }

        private static void AddSummary(string summary, ref StringBuilder stringBuilder)
        {
            stringBuilder.AppendLine($"\t\t/// <summary> {summary} </summary>");
        }

        public static void ScratchBlockClass(ref StringBuilder stringBuilder, List<BlockData> blockDatas)
        {
            List<ScratchValueType> inputs = new List<ScratchValueType>();
            List<ScratchValueType> returns = new List<ScratchValueType>();
            for (int i = 0; i < blockDatas.Count; i++)
            {
                GetInputValuesLen(blockDatas[i], ref inputs, ref returns);

                stringBuilder.AppendLine($"\tpublic partial class BlockLogic_{blockDatas[i].ScratchType} {GetInterfaceName(blockDatas[i].Type)}");
                stringBuilder.AppendLine("\t{");
                stringBuilder.AppendLine($"\t\tpublic ScratchClassName ClassName => ScratchClassName.{blockDatas[i].Type};");
                stringBuilder.AppendLine($"\t\tpublic ScratchBlockType Type => ScratchBlockType.{blockDatas[i].ScratchType};");
                
                stringBuilder.AppendLine($"\t\tprivate BVector3 m_CanvasPos = BVector3.zero;");
                stringBuilder.AppendLine($"\t\tpublic BVector3 CanvasPos");
                stringBuilder.AppendLine("\t\t{");
                stringBuilder.AppendLine("\t\t\tget => m_CanvasPos;");
                stringBuilder.AppendLine("\t\t\tset");
                stringBuilder.AppendLine("\t\t\t{");
                stringBuilder.AppendLine("\t\t\tSetCanvasPos(ref value);");
                stringBuilder.AppendLine("\t\t\tm_CanvasPos = value;");
                stringBuilder.AppendLine("\t\t\t}");
                stringBuilder.AppendLine("\t\t}");
                stringBuilder.AppendLine("\t\tpartial void SetCanvasPos(ref BVector3 newData);");
                
                stringBuilder.AppendLine($"\t\tprivate int m_NextBlockGuid = -1;");
                stringBuilder.AppendLine($"\t\tpublic int NextBlockGuid");
                stringBuilder.AppendLine("\t\t{");
                stringBuilder.AppendLine("\t\t\tget => m_NextBlockGuid;");
                stringBuilder.AppendLine("\t\t\tset");
                stringBuilder.AppendLine("\t\t\t{");
                stringBuilder.AppendLine("\t\t\tSetNextBlockGuid(ref value);");
                stringBuilder.AppendLine("\t\t\tm_NextBlockGuid = value;");
                stringBuilder.AppendLine("\t\t\t}");
                stringBuilder.AppendLine("\t\t}");
                stringBuilder.AppendLine("\t\tpartial void SetNextBlockGuid(ref int newData);");

                stringBuilder.AppendLine($"\t\tprivate IEngineBlockBaseData m_NextBlock;");
                stringBuilder.AppendLine($"\t\tpublic IEngineBlockBaseData NextBlock");
                stringBuilder.AppendLine("\t\t{");
                stringBuilder.AppendLine("\t\t\tget => m_NextBlock;");
                stringBuilder.AppendLine("\t\t\tset");
                stringBuilder.AppendLine("\t\t\t{");
                stringBuilder.AppendLine("\t\t\tSetNextBlock(ref value);");
                stringBuilder.AppendLine("\t\t\tm_NextBlock = value;");
                stringBuilder.AppendLine("\t\t\t}");
                stringBuilder.AppendLine("\t\t}");
                stringBuilder.AppendLine("\t\tpartial void SetNextBlock(ref IEngineBlockBaseData newData);");

                stringBuilder.AppendLine($"\t\tprivate int m_Guid = -1;");
                stringBuilder.AppendLine($"\t\tpublic int Guid");
                stringBuilder.AppendLine("\t\t{");
                stringBuilder.AppendLine("\t\t\tget => m_Guid;");
                stringBuilder.AppendLine("\t\t\tset");
                stringBuilder.AppendLine("\t\t\t{");
                stringBuilder.AppendLine("\t\t\tSetGuid(ref value);");
                stringBuilder.AppendLine("\t\t\tm_Guid = value;");
                stringBuilder.AppendLine("\t\t\t}");
                stringBuilder.AppendLine("\t\t}");
                stringBuilder.AppendLine("\t\tpartial void SetGuid(ref int newData);");

                GetInterfaceProperty(ref stringBuilder, blockDatas[i].Type);


                stringBuilder.AppendLine("\t\t#region IBlockVarGuid");

                //InputValue

                for (int j = 0; j < inputs.Count; j++)
                {
                    stringBuilder.AppendLine("\t\tprivate string m_InputValue_" + j + " = string.Empty;");

                    stringBuilder.AppendLine("\t\tpublic string InputValue_" + j);
                    stringBuilder.AppendLine("\t\t{");
                    stringBuilder.AppendLine("\t\t\tget => m_InputValue_" + j + ";");
                    stringBuilder.AppendLine("\t\t\tset");
                    stringBuilder.AppendLine("\t\t\t{");
                    stringBuilder.AppendLine("\t\t\tSetInputValue_" + j + "(ref value);");
                    stringBuilder.AppendLine("\t\t\tm_InputValue_" + j + " = value;");
                    stringBuilder.AppendLine("\t\t\t}");
                    stringBuilder.AppendLine("\t\t}");


                    stringBuilder.AppendLine("\t\tpartial void SetInputValue_" + j + "(ref string newData);");
                }

                stringBuilder.AppendLine($"\t\tpublic void {nameof(IBlockVarGuid.SetInputValues)}(int index, string value)");
                stringBuilder.AppendLine("\t\t{");
                stringBuilder.AppendLine("\t\t\tswitch(index)");
                stringBuilder.AppendLine("\t\t\t{");
                for (int j = 0; j < inputs.Count; j++)
                {
                    stringBuilder.AppendLine("\t\t\t\tcase " + j + ":");
                    stringBuilder.AppendLine("\t\t\t\t\tInputValue_" + j + " = value;");
                    stringBuilder.AppendLine("\t\t\t\t\tbreak;");
                }

                stringBuilder.AppendLine("\t\t\t}");
                stringBuilder.AppendLine("\t\t}");

                stringBuilder.AppendLine($"\t\tpublic string {nameof(IBlockVarGuid.GetInputValue)}(int index)");
                stringBuilder.AppendLine("\t\t{");
                stringBuilder.AppendLine("\t\t\tswitch(index)");
                stringBuilder.AppendLine("\t\t\t{");
                for (int j = 0; j < inputs.Count; j++)
                {
                    stringBuilder.AppendLine("\t\t\t\tcase " + j + ":");
                    stringBuilder.AppendLine("\t\t\t\t\treturn InputValue_" + j + ";");
                }

                stringBuilder.AppendLine("\t\t\t}");
                stringBuilder.AppendLine("\t\t\treturn string.Empty;");
                stringBuilder.AppendLine("\t\t}");

                stringBuilder.AppendLine($"\t\tpublic string[] {nameof(IBlockVarGuid.GetInputValues)}()");
                stringBuilder.AppendLine("\t\t{");
                stringBuilder.AppendLine("\t\t\tstring[] values = new string[" + inputs.Count + "];");
                for (int j = 0; j < inputs.Count; j++)
                {
                    stringBuilder.AppendLine("\t\t\tvalues[" + j + "] = InputValue_" + j + ";");
                }

                stringBuilder.AppendLine("\t\t\treturn values;");
                stringBuilder.AppendLine("\t\t}");


                //VarGuid

                for (int j = 0; j < inputs.Count; j++)
                {
                    stringBuilder.AppendLine("\t\tprivate int m_VarGuid_" + j + " = -1;");

                    stringBuilder.AppendLine("\t\tpublic int VarGuid_" + j);
                    stringBuilder.AppendLine("\t\t{");
                    stringBuilder.AppendLine("\t\t\tget => m_VarGuid_" + j + ";");
                    stringBuilder.AppendLine("\t\t\tset");
                    stringBuilder.AppendLine("\t\t\t{");
                    stringBuilder.AppendLine("\t\t\tSetVarGuid_" + j + "(ref value);");
                    stringBuilder.AppendLine("\t\t\tm_VarGuid_" + j + " = value;");
                    stringBuilder.AppendLine("\t\t\t}");
                    stringBuilder.AppendLine("\t\t}");


                    stringBuilder.AppendLine("\t\tpartial void SetVarGuid_" + j + "(ref int newData);");
                }

                stringBuilder.AppendLine($"\t\tpublic int {nameof(IBlockVarGuid.GetVarGuidsLength)}()=> {inputs.Count};");
                stringBuilder.AppendLine($"\t\tpublic void {nameof(IBlockVarGuid.SetVarsGuid)}(int index, int value)");
                stringBuilder.AppendLine("\t\t{");
                stringBuilder.AppendLine("\t\t\tswitch(index)");
                stringBuilder.AppendLine("\t\t\t{");
                for (int j = 0; j < inputs.Count; j++)
                {
                    stringBuilder.AppendLine("\t\t\t\tcase " + j + ":");
                    stringBuilder.AppendLine("\t\t\t\t\tVarGuid_" + j + " = value;");
                    stringBuilder.AppendLine("\t\t\t\t\tbreak;");
                }

                stringBuilder.AppendLine("\t\t\t}");
                stringBuilder.AppendLine("\t\t}");

                stringBuilder.AppendLine($"\t\tpublic int {nameof(IBlockVarGuid.GetVarGuid)}(int index)");
                stringBuilder.AppendLine("\t\t{");
                stringBuilder.AppendLine("\t\t\tswitch(index)");
                stringBuilder.AppendLine("\t\t\t{");
                for (int j = 0; j < inputs.Count; j++)
                {
                    stringBuilder.AppendLine("\t\t\t\tcase " + j + ":");
                    stringBuilder.AppendLine("\t\t\t\t\treturn VarGuid_" + j + ";");
                }

                stringBuilder.AppendLine("\t\t\t}");
                stringBuilder.AppendLine("\t\t\treturn -1;");
                stringBuilder.AppendLine("\t\t}");

                stringBuilder.AppendLine($"\t\tpublic int[] {nameof(IBlockVarGuid.GetVarGuids)}()");
                stringBuilder.AppendLine("\t\t{");
                stringBuilder.AppendLine("\t\t\tint[] values = new int[" + inputs.Count + "];");
                for (int j = 0; j < inputs.Count; j++)
                {
                    stringBuilder.AppendLine("\t\t\tvalues[" + j + "] = VarGuid_" + j + ";");
                }

                stringBuilder.AppendLine("\t\t\treturn values;");
                stringBuilder.AppendLine("\t\t}");


                stringBuilder.AppendLine("\t\t#endregion");


                stringBuilder.AppendLine("\t\t#region IBlockReturnVarGuid");

                //ReturnVarGuid

                for (int j = 0; j < returns.Count; j++)
                {
                    stringBuilder.AppendLine("\t\tprivate int m_ReturnVarGuid_" + j + " = -1;");
                    AddSummary($"{returns[j]}_{j}", ref stringBuilder);
                    stringBuilder.AppendLine("\t\tpublic int ReturnVarGuid_" + j);
                    stringBuilder.AppendLine("\t\t{");
                    stringBuilder.AppendLine("\t\t\tget => m_ReturnVarGuid_" + j + ";");
                    stringBuilder.AppendLine("\t\t\tset");
                    stringBuilder.AppendLine("\t\t\t{");
                    stringBuilder.AppendLine("\t\t\tSetReturnVarGuid_" + j + "(ref value);");
                    stringBuilder.AppendLine("\t\t\tm_ReturnVarGuid_" + j + " = value;");
                    stringBuilder.AppendLine("\t\t\t}");
                    stringBuilder.AppendLine("\t\t}");

                    AddSummary($"{returns[j]}_{j}", ref stringBuilder);
                    stringBuilder.AppendLine("\t\tpartial void SetReturnVarGuid_" + j + "(ref int newData);");
                }

                stringBuilder.AppendLine($"\t\tpublic int {nameof(IBlockReturnVarGuid.GetReturnValuesLength)}()=> {returns.Count};");
                stringBuilder.AppendLine($"\t\tpublic void {nameof(IBlockReturnVarGuid.SetReturnValueGuid)}(int index, int value)");
                stringBuilder.AppendLine("\t\t{");
                stringBuilder.AppendLine("\t\t\tswitch(index)");
                stringBuilder.AppendLine("\t\t\t{");
                for (int j = 0; j < returns.Count; j++)
                {
                    stringBuilder.AppendLine("\t\t\t\tcase " + j + ":");
                    stringBuilder.AppendLine("\t\t\t\t\tReturnVarGuid_" + j + " = value;");
                    stringBuilder.AppendLine("\t\t\t\t\tbreak;");
                }

                stringBuilder.AppendLine("\t\t\t}");
                stringBuilder.AppendLine("\t\t}");

                stringBuilder.AppendLine($"\t\tpublic int {nameof(IBlockReturnVarGuid.GetReturnValueGuid)}(int index)");
                stringBuilder.AppendLine("\t\t{");
                stringBuilder.AppendLine("\t\t\tswitch(index)");
                stringBuilder.AppendLine("\t\t\t{");
                for (int j = 0; j < returns.Count; j++)
                {
                    stringBuilder.AppendLine("\t\t\t\tcase " + j + ":");
                    stringBuilder.AppendLine("\t\t\t\t\treturn ReturnVarGuid_" + j + ";");
                }

                stringBuilder.AppendLine("\t\t\t}");
                stringBuilder.AppendLine("\t\t\treturn -1;");
                stringBuilder.AppendLine("\t\t}");

                stringBuilder.AppendLine($"\t\tpublic int[] {nameof(IBlockReturnVarGuid.GetReturnValues)}()");
                stringBuilder.AppendLine("\t\t{");
                stringBuilder.AppendLine("\t\t\tint[] values = new int[" + returns.Count + "];");
                for (int j = 0; j < returns.Count; j++)
                {
                    stringBuilder.AppendLine("\t\t\tvalues[" + j + "] = ReturnVarGuid_" + j + ";");
                }

                stringBuilder.AppendLine("\t\t\treturn values;");
                stringBuilder.AppendLine("\t\t}");


                stringBuilder.AppendLine("\t\t#endregion");


                stringBuilder.AppendLine("\t}");
            }
        }

        private static bool ExportConfigTableCS(string filePath, StringBuilder stringBuilder)
        {
            string md5ResCs = String.Empty;
            StringBuilder readBuilder = new StringBuilder();
            using (StreamReader reader = new StreamReader(filePath, Encoding.UTF8, false))
            {
                while (!reader.EndOfStream)
                {
                    readBuilder.AppendLine(reader.ReadLine());
                }
            }

            md5ResCs = GetFileContentMd5(readBuilder.ToString());

            String newMd5 = GetFileContentMd5(stringBuilder.ToString());
            // Debug.LogError(readBuilder.ToString() +":" +stringBuilder.ToString() );
            // Debug.LogError(md5ResCs +":"+newMd5 + ":"+readBuilder.ToString().Length +":" +stringBuilder.ToString().Length );
            if (!newMd5.Equals(md5ResCs))
            {
                using (StreamWriter writer = new StreamWriter(filePath, false, Encoding.UTF8))
                {
                    writer.Write(stringBuilder.ToString());
                }

                return true;
            }

            return false;
        }

        private static string GetFileContentMd5(string content)
        {
            byte[] result = Encoding.UTF8.GetBytes(content);
            MD5 md5 = MD5.Create();
            byte[] md5Res = md5.ComputeHash(result);
            StringBuilder md5ResString = new StringBuilder();
            for (int i = 0; i < md5Res.Length; i++)
            {
                md5ResString.Append(md5Res[i].ToString("x2"));
            }

            return md5ResString.ToString();
        }


        [MenuItem("Assets/Scratch/Convert Prefabs", false, 80)]
        public static void Editor_Convert_Prefabs()
        {
            string[] strs = Selection.assetGUIDs;
            if (strs == null || strs.Length == 0) return;

            for (int i = 0; i < strs.Length; i++)
            {
                string path = AssetDatabase.GUIDToAssetPath(strs[i]);

                TextAsset textAsset = AssetDatabase.LoadAssetAtPath<TextAsset>(path);
                Block block = ScratchUtils.DeserializeBlock(textAsset.bytes);

                string newPath = path.Replace(".bytes", ".prefab");
                var localPath = AssetDatabase.GenerateUniqueAssetPath(newPath);

                bool prefabSuccess;
                PrefabUtility.SaveAsPrefabAsset(block.gameObject, localPath, out prefabSuccess);

                GameObject.DestroyImmediate(block.gameObject);
            }

            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
        }
    }
}