//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
namespace ScratchFramework
{
	public static class EngineBlockCodeExtension
	{
		/// <summary> BlockData Template Dict </summary>
		public static Dictionary<int, int> TemplateDict = new Dictionary<int, int>()
		{
			{(int)ScratchBlockType.ApplyForce, 0},
			{(int)ScratchBlockType.CompareValues, 1},
			{(int)ScratchBlockType.DestroyObject, 2},
			{(int)ScratchBlockType.EntityValue, 3},
			{(int)ScratchBlockType.GetCharacterSpeed, 4},
			{(int)ScratchBlockType.GetVectorMagnitude, 5},
			{(int)ScratchBlockType.IfElse, 6},
			{(int)ScratchBlockType.IntegerValue, 7},
			{(int)ScratchBlockType.OnCollisionEnter, 8},
			{(int)ScratchBlockType.OnCollisionExit, 9},
			{(int)ScratchBlockType.OnCollisionStay, 10},
			{(int)ScratchBlockType.OnObjectCreated, 11},
			{(int)ScratchBlockType.RepeatAction, 12},
			{(int)ScratchBlockType.StartCountdown, 13},
			{(int)ScratchBlockType.VectorValue, 14},
		};
		/// <summary> BlockData Logic </summary>
		public static IEngineBlockBaseData CreateBlockData(this ScratchBlockType type)
		{
			switch (type)
			{
				case ScratchBlockType.ApplyForce: return new BlockLogic_ApplyForce();
				case ScratchBlockType.CompareValues: return new BlockLogic_CompareValues();
				case ScratchBlockType.DestroyObject: return new BlockLogic_DestroyObject();
				case ScratchBlockType.EntityValue: return new BlockLogic_EntityValue();
				case ScratchBlockType.GetCharacterSpeed: return new BlockLogic_GetCharacterSpeed();
				case ScratchBlockType.GetVectorMagnitude: return new BlockLogic_GetVectorMagnitude();
				case ScratchBlockType.IfElse: return new BlockLogic_IfElse();
				case ScratchBlockType.IntegerValue: return new BlockLogic_IntegerValue();
				case ScratchBlockType.OnCollisionEnter: return new BlockLogic_OnCollisionEnter();
				case ScratchBlockType.OnCollisionExit: return new BlockLogic_OnCollisionExit();
				case ScratchBlockType.OnCollisionStay: return new BlockLogic_OnCollisionStay();
				case ScratchBlockType.OnObjectCreated: return new BlockLogic_OnObjectCreated();
				case ScratchBlockType.RepeatAction: return new BlockLogic_RepeatAction();
				case ScratchBlockType.StartCountdown: return new BlockLogic_StartCountdown();
				case ScratchBlockType.VectorValue: return new BlockLogic_VectorValue();
			}
			 return null;
		}
	}
	public partial class BlockLogic_ApplyForce : IEngineBlockSimpleBase
	{
		/// <summary> [Editor Data]功能类型 </summary>
		public FucType FucType => FucType.Action;
		/// <summary> [Editor Data]逻辑类型 </summary>
		public ScratchBlockType Type => ScratchBlockType.ApplyForce;
		/// <summary> [Editor Data]UI类型 </summary>
		public BlockType BlockType => BlockType.Simple;
		/// <summary> [Editor Data]是否为画布根 </summary>
		public bool IsRoot { get; set; } = false;
		/// <summary> [Editor Data]画布位置(需判断画布根时有效) </summary>
		public BVector2 CanvasPos { get; set; } = BVector2.zero;
		private bool m_Enable = true;
		/// <summary> [Editor Data]编辑器逻辑是否Enable </summary>
		public bool Enable
		{
			get => m_Enable;
			set
			{
				SetEnable(ref value);
				m_Enable = value;
			}
		}
		partial void SetEnable(ref bool newData);
		private BGuid m_Guid = BGuid.Empty;
		/// <summary> [Editor Data]Guid </summary>
		public int Guid
		{
			get => m_Guid.GetGuid();
			set
			{
				SetGuid(ref value);
				m_Guid.SetGuid(value,out m_Guid);
			}
		}
		partial void SetGuid(ref int newData);
		private BGuid m_NextGuid = BGuid.Empty;
		/// <summary> [Editor Data]NextGuid </summary>
		public int NextGuid
		{
			get => m_NextGuid.GetGuid();
			set
			{
				SetNextGuid(ref value);
				m_NextGuid.SetGuid(value,out m_NextGuid);
			}
		}
		partial void SetNextGuid(ref int newData);
		private BGuid m_VarGuid_0 = BGuid.Empty;
		/// <summary> [Editor Data]Entity </summary>
		public int VarGuid_0
		{
			get => m_VarGuid_0.GetGuid();
			set
			{
				SetVarGuid_0(ref value);
				m_VarGuid_0.SetGuid(value,out m_VarGuid_0);
			}
		}
		/// <summary> Entity </summary>
		partial void SetVarGuid_0(ref int newData);
		private BGuid m_VarGuid_1 = BGuid.Empty;
		/// <summary> [Editor Data]Vector3 </summary>
		public int VarGuid_1
		{
			get => m_VarGuid_1.GetGuid();
			set
			{
				SetVarGuid_1(ref value);
				m_VarGuid_1.SetGuid(value,out m_VarGuid_1);
			}
		}
		/// <summary> Vector3 </summary>
		partial void SetVarGuid_1(ref int newData);
		/// <summary> 获取输入变量长度 </summary>
		public int GetVarGuidsLength()=> 2;
		/// <summary> 设置输入变量Guid </summary>
		public void SetVarsGuid(int index, int value)
		{
			switch(index)
			{
				case 0:
					VarGuid_0 = value;
					break;
				case 1:
					VarGuid_1 = value;
					break;
			}
		}
		/// <summary> 获取返回值变量Guid </summary>
		public int GetVarGuid(int index)
		{
			switch(index)
			{
				case 0:
					return VarGuid_0;
				case 1:
					return VarGuid_1;
			}
			return 0;
		}
		/// <summary> 获取变量Guid数组 </summary>
		public int[] GetVarGuids()
		{
			int[] values = new int[2];
			values[0] = VarGuid_0;
			values[1] = VarGuid_1;
			return values;
		}
		private int[] m_Guids = null;
		public int[] GetGuids()
		{
			if (m_Guids == null)
			{
				int guidLen = 4;
				m_Guids = new int[guidLen];
				int index = 0;
				m_Guids[index] = Guid;
				index++;
				m_Guids[index] = NextGuid;
				index++;
				m_Guids[index] = VarGuid_0;
				index++;
				m_Guids[index] = VarGuid_1;

			}
			else
			{
				int guidLen = 4;
				if (guidLen != m_Guids.Length)
				{
					m_Guids = new int[guidLen];
				}
				int index = 0;
				m_Guids[index] = Guid;
				index++;
				m_Guids[index] = NextGuid;
				index++;
				m_Guids[index] = VarGuid_0;
				index++;
				m_Guids[index] = VarGuid_1;

			}
			return m_Guids;
		}
		public void RefreshGuids(Dictionary<int, int> map)
		{
			if (Guid != ScratchUtils.InvalidGuid && map.ContainsKey(Guid)) Guid = map[Guid];
			if (NextGuid != ScratchUtils.InvalidGuid && map.ContainsKey(NextGuid)) NextGuid = map[NextGuid];
			if (VarGuid_0 != ScratchUtils.InvalidGuid && map.ContainsKey(VarGuid_0)) VarGuid_0 = map[VarGuid_0];
			if (VarGuid_1 != ScratchUtils.InvalidGuid && map.ContainsKey(VarGuid_1)) VarGuid_1 = map[VarGuid_1];

		}
	}
	public partial class BlockLogic_CompareValues : IEngineBlockOperationBase
	{
		/// <summary> [Editor Data]功能类型 </summary>
		public FucType FucType => FucType.Condition;
		/// <summary> [Editor Data]逻辑类型 </summary>
		public ScratchBlockType Type => ScratchBlockType.CompareValues;
		/// <summary> [Editor Data]UI类型 </summary>
		public BlockType BlockType => BlockType.Operation;
		/// <summary> [Editor Data]是否为画布根 </summary>
		public bool IsRoot { get; set; } = false;
		/// <summary> [Editor Data]画布位置(需判断画布根时有效) </summary>
		public BVector2 CanvasPos { get; set; } = BVector2.zero;
		private bool m_Enable = true;
		/// <summary> [Editor Data]编辑器逻辑是否Enable </summary>
		public bool Enable
		{
			get => m_Enable;
			set
			{
				SetEnable(ref value);
				m_Enable = value;
			}
		}
		partial void SetEnable(ref bool newData);
		private BGuid m_Guid = BGuid.Empty;
		/// <summary> [Editor Data]Guid </summary>
		public int Guid
		{
			get => m_Guid.GetGuid();
			set
			{
				SetGuid(ref value);
				m_Guid.SetGuid(value,out m_Guid);
			}
		}
		partial void SetGuid(ref int newData);
		private BGuid m_VarGuid_0 = BGuid.Empty;
		/// <summary> [Editor Data]Object </summary>
		public int VarGuid_0
		{
			get => m_VarGuid_0.GetGuid();
			set
			{
				SetVarGuid_0(ref value);
				m_VarGuid_0.SetGuid(value,out m_VarGuid_0);
			}
		}
		/// <summary> Object </summary>
		partial void SetVarGuid_0(ref int newData);
		private BGuid m_VarGuid_1 = BGuid.Empty;
		/// <summary> [Editor Data]Object </summary>
		public int VarGuid_1
		{
			get => m_VarGuid_1.GetGuid();
			set
			{
				SetVarGuid_1(ref value);
				m_VarGuid_1.SetGuid(value,out m_VarGuid_1);
			}
		}
		/// <summary> Object </summary>
		partial void SetVarGuid_1(ref int newData);
		/// <summary> 获取输入变量长度 </summary>
		public int GetVarGuidsLength()=> 2;
		/// <summary> 设置输入变量Guid </summary>
		public void SetVarsGuid(int index, int value)
		{
			switch(index)
			{
				case 0:
					VarGuid_0 = value;
					break;
				case 1:
					VarGuid_1 = value;
					break;
			}
		}
		/// <summary> 获取返回值变量Guid </summary>
		public int GetVarGuid(int index)
		{
			switch(index)
			{
				case 0:
					return VarGuid_0;
				case 1:
					return VarGuid_1;
			}
			return 0;
		}
		/// <summary> 获取变量Guid数组 </summary>
		public int[] GetVarGuids()
		{
			int[] values = new int[2];
			values[0] = VarGuid_0;
			values[1] = VarGuid_1;
			return values;
		}
		private int[] m_Guids = null;
		public int[] GetGuids()
		{
			if (m_Guids == null)
			{
				int guidLen = 3;
				m_Guids = new int[guidLen];
				int index = 0;
				m_Guids[index] = Guid;
				index++;
				m_Guids[index] = VarGuid_0;
				index++;
				m_Guids[index] = VarGuid_1;

			}
			else
			{
				int guidLen = 3;
				if (guidLen != m_Guids.Length)
				{
					m_Guids = new int[guidLen];
				}
				int index = 0;
				m_Guids[index] = Guid;
				index++;
				m_Guids[index] = VarGuid_0;
				index++;
				m_Guids[index] = VarGuid_1;

			}
			return m_Guids;
		}
		public void RefreshGuids(Dictionary<int, int> map)
		{
			if (Guid != ScratchUtils.InvalidGuid && map.ContainsKey(Guid)) Guid = map[Guid];
			if (VarGuid_0 != ScratchUtils.InvalidGuid && map.ContainsKey(VarGuid_0)) VarGuid_0 = map[VarGuid_0];
			if (VarGuid_1 != ScratchUtils.InvalidGuid && map.ContainsKey(VarGuid_1)) VarGuid_1 = map[VarGuid_1];

		}
	}
	public partial class BlockLogic_DestroyObject : IEngineBlockSimpleBase
	{
		/// <summary> [Editor Data]功能类型 </summary>
		public FucType FucType => FucType.Action;
		/// <summary> [Editor Data]逻辑类型 </summary>
		public ScratchBlockType Type => ScratchBlockType.DestroyObject;
		/// <summary> [Editor Data]UI类型 </summary>
		public BlockType BlockType => BlockType.Simple;
		/// <summary> [Editor Data]是否为画布根 </summary>
		public bool IsRoot { get; set; } = false;
		/// <summary> [Editor Data]画布位置(需判断画布根时有效) </summary>
		public BVector2 CanvasPos { get; set; } = BVector2.zero;
		private bool m_Enable = true;
		/// <summary> [Editor Data]编辑器逻辑是否Enable </summary>
		public bool Enable
		{
			get => m_Enable;
			set
			{
				SetEnable(ref value);
				m_Enable = value;
			}
		}
		partial void SetEnable(ref bool newData);
		private BGuid m_Guid = BGuid.Empty;
		/// <summary> [Editor Data]Guid </summary>
		public int Guid
		{
			get => m_Guid.GetGuid();
			set
			{
				SetGuid(ref value);
				m_Guid.SetGuid(value,out m_Guid);
			}
		}
		partial void SetGuid(ref int newData);
		private BGuid m_NextGuid = BGuid.Empty;
		/// <summary> [Editor Data]NextGuid </summary>
		public int NextGuid
		{
			get => m_NextGuid.GetGuid();
			set
			{
				SetNextGuid(ref value);
				m_NextGuid.SetGuid(value,out m_NextGuid);
			}
		}
		partial void SetNextGuid(ref int newData);
		private BGuid m_VarGuid_0 = BGuid.Empty;
		/// <summary> [Editor Data]Entity </summary>
		public int VarGuid_0
		{
			get => m_VarGuid_0.GetGuid();
			set
			{
				SetVarGuid_0(ref value);
				m_VarGuid_0.SetGuid(value,out m_VarGuid_0);
			}
		}
		/// <summary> Entity </summary>
		partial void SetVarGuid_0(ref int newData);
		/// <summary> 获取输入变量长度 </summary>
		public int GetVarGuidsLength()=> 1;
		/// <summary> 设置输入变量Guid </summary>
		public void SetVarsGuid(int index, int value)
		{
			switch(index)
			{
				case 0:
					VarGuid_0 = value;
					break;
			}
		}
		/// <summary> 获取返回值变量Guid </summary>
		public int GetVarGuid(int index)
		{
			switch(index)
			{
				case 0:
					return VarGuid_0;
			}
			return 0;
		}
		/// <summary> 获取变量Guid数组 </summary>
		public int[] GetVarGuids()
		{
			int[] values = new int[1];
			values[0] = VarGuid_0;
			return values;
		}
		private int[] m_Guids = null;
		public int[] GetGuids()
		{
			if (m_Guids == null)
			{
				int guidLen = 3;
				m_Guids = new int[guidLen];
				int index = 0;
				m_Guids[index] = Guid;
				index++;
				m_Guids[index] = NextGuid;
				index++;
				m_Guids[index] = VarGuid_0;

			}
			else
			{
				int guidLen = 3;
				if (guidLen != m_Guids.Length)
				{
					m_Guids = new int[guidLen];
				}
				int index = 0;
				m_Guids[index] = Guid;
				index++;
				m_Guids[index] = NextGuid;
				index++;
				m_Guids[index] = VarGuid_0;

			}
			return m_Guids;
		}
		public void RefreshGuids(Dictionary<int, int> map)
		{
			if (Guid != ScratchUtils.InvalidGuid && map.ContainsKey(Guid)) Guid = map[Guid];
			if (NextGuid != ScratchUtils.InvalidGuid && map.ContainsKey(NextGuid)) NextGuid = map[NextGuid];
			if (VarGuid_0 != ScratchUtils.InvalidGuid && map.ContainsKey(VarGuid_0)) VarGuid_0 = map[VarGuid_0];

		}
	}
	public partial class BlockLogic_EntityValue : IEngineBlockVariableBase
	{
		/// <summary> [Editor Data]功能类型 </summary>
		public FucType FucType => FucType.Variable;
		/// <summary> [Editor Data]逻辑类型 </summary>
		public ScratchBlockType Type => ScratchBlockType.EntityValue;
		/// <summary> [Editor Data]UI类型 </summary>
		public BlockType BlockType => BlockType.Operation;
		private bool m_Enable = true;
		/// <summary> [Editor Data]编辑器逻辑是否Enable </summary>
		public bool Enable
		{
			get => m_Enable;
			set
			{
				SetEnable(ref value);
				m_Enable = value;
			}
		}
		partial void SetEnable(ref bool newData);
		private BGuid m_Guid = BGuid.Empty;
		/// <summary> [Editor Data]Guid </summary>
		public int Guid
		{
			get => m_Guid.GetGuid();
			set
			{
				SetGuid(ref value);
				m_Guid.SetGuid(value,out m_Guid);
			}
		}
		partial void SetGuid(ref int newData);
		private ScratchFramework.ScratchValueType m_ValueType = ScratchValueType.EntityRef;
		public ScratchFramework.ScratchValueType ValueType
		{
			get => m_ValueType;
		}
		partial void SetValueType(ref ScratchFramework.ScratchValueType newData);
		private System.String m_VariableName = null;
		public System.String VariableName
		{
			get => m_VariableName;
			set
			{
				SetVariableName(ref value);
				m_VariableName = value;
			}
		}
		partial void SetVariableName(ref System.String newData);
		private System.Object m_VariableValue = null;
		public System.Object VariableValue
		{
			get => m_VariableValue;
			set
			{
				SetVariableValue(ref value);
				m_VariableValue = value;
			}
		}
		partial void SetVariableValue(ref System.Object newData);
		private BGuid m_ReturnParentGuid = BGuid.Empty;
		/// <summary> [Editor Data]NextGuid </summary>
		public int ReturnParentGuid
		{
			get => m_ReturnParentGuid.GetGuid();
			set
			{
				SetReturnParentGuid(ref value);
				m_ReturnParentGuid.SetGuid(value,out m_ReturnParentGuid);
			}
		}
		partial void SetReturnParentGuid(ref System.Int32 newData);
		private int[] m_Guids = null;
		public int[] GetGuids()
		{
			if (m_Guids == null)
			{
				int guidLen = 2;
				m_Guids = new int[guidLen];
				int index = 0;
				m_Guids[index] = Guid;
				index++;
				m_Guids[index] = ReturnParentGuid;

			}
			else
			{
				int guidLen = 2;
				if (guidLen != m_Guids.Length)
				{
					m_Guids = new int[guidLen];
				}
				int index = 0;
				m_Guids[index] = Guid;
				index++;
				m_Guids[index] = ReturnParentGuid;

			}
			return m_Guids;
		}
		public void RefreshGuids(Dictionary<int, int> map)
		{
			if (Guid != ScratchUtils.InvalidGuid && map.ContainsKey(Guid)) Guid = map[Guid];
			if (ReturnParentGuid != ScratchUtils.InvalidGuid && map.ContainsKey(ReturnParentGuid)) ReturnParentGuid = map[ReturnParentGuid];

		}
	}
	public partial class BlockLogic_GetCharacterSpeed : IEngineBlockOperationBase
	{
		/// <summary> [Editor Data]功能类型 </summary>
		public FucType FucType => FucType.GetValue;
		/// <summary> [Editor Data]逻辑类型 </summary>
		public ScratchBlockType Type => ScratchBlockType.GetCharacterSpeed;
		/// <summary> [Editor Data]UI类型 </summary>
		public BlockType BlockType => BlockType.Operation;
		/// <summary> [Editor Data]是否为画布根 </summary>
		public bool IsRoot { get; set; } = false;
		/// <summary> [Editor Data]画布位置(需判断画布根时有效) </summary>
		public BVector2 CanvasPos { get; set; } = BVector2.zero;
		private bool m_Enable = true;
		/// <summary> [Editor Data]编辑器逻辑是否Enable </summary>
		public bool Enable
		{
			get => m_Enable;
			set
			{
				SetEnable(ref value);
				m_Enable = value;
			}
		}
		partial void SetEnable(ref bool newData);
		private BGuid m_Guid = BGuid.Empty;
		/// <summary> [Editor Data]Guid </summary>
		public int Guid
		{
			get => m_Guid.GetGuid();
			set
			{
				SetGuid(ref value);
				m_Guid.SetGuid(value,out m_Guid);
			}
		}
		partial void SetGuid(ref int newData);
		private BGuid m_VarGuid_0 = BGuid.Empty;
		/// <summary> [Editor Data]Entity </summary>
		public int VarGuid_0
		{
			get => m_VarGuid_0.GetGuid();
			set
			{
				SetVarGuid_0(ref value);
				m_VarGuid_0.SetGuid(value,out m_VarGuid_0);
			}
		}
		/// <summary> Entity </summary>
		partial void SetVarGuid_0(ref int newData);
		/// <summary> 获取输入变量长度 </summary>
		public int GetVarGuidsLength()=> 1;
		/// <summary> 设置输入变量Guid </summary>
		public void SetVarsGuid(int index, int value)
		{
			switch(index)
			{
				case 0:
					VarGuid_0 = value;
					break;
			}
		}
		/// <summary> 获取返回值变量Guid </summary>
		public int GetVarGuid(int index)
		{
			switch(index)
			{
				case 0:
					return VarGuid_0;
			}
			return 0;
		}
		/// <summary> 获取变量Guid数组 </summary>
		public int[] GetVarGuids()
		{
			int[] values = new int[1];
			values[0] = VarGuid_0;
			return values;
		}
		private int[] m_Guids = null;
		public int[] GetGuids()
		{
			if (m_Guids == null)
			{
				int guidLen = 2;
				m_Guids = new int[guidLen];
				int index = 0;
				m_Guids[index] = Guid;
				index++;
				m_Guids[index] = VarGuid_0;

			}
			else
			{
				int guidLen = 2;
				if (guidLen != m_Guids.Length)
				{
					m_Guids = new int[guidLen];
				}
				int index = 0;
				m_Guids[index] = Guid;
				index++;
				m_Guids[index] = VarGuid_0;

			}
			return m_Guids;
		}
		public void RefreshGuids(Dictionary<int, int> map)
		{
			if (Guid != ScratchUtils.InvalidGuid && map.ContainsKey(Guid)) Guid = map[Guid];
			if (VarGuid_0 != ScratchUtils.InvalidGuid && map.ContainsKey(VarGuid_0)) VarGuid_0 = map[VarGuid_0];

		}
	}
	public partial class BlockLogic_GetVectorMagnitude : IEngineBlockOperationBase
	{
		/// <summary> [Editor Data]功能类型 </summary>
		public FucType FucType => FucType.GetValue;
		/// <summary> [Editor Data]逻辑类型 </summary>
		public ScratchBlockType Type => ScratchBlockType.GetVectorMagnitude;
		/// <summary> [Editor Data]UI类型 </summary>
		public BlockType BlockType => BlockType.Operation;
		/// <summary> [Editor Data]是否为画布根 </summary>
		public bool IsRoot { get; set; } = false;
		/// <summary> [Editor Data]画布位置(需判断画布根时有效) </summary>
		public BVector2 CanvasPos { get; set; } = BVector2.zero;
		private bool m_Enable = true;
		/// <summary> [Editor Data]编辑器逻辑是否Enable </summary>
		public bool Enable
		{
			get => m_Enable;
			set
			{
				SetEnable(ref value);
				m_Enable = value;
			}
		}
		partial void SetEnable(ref bool newData);
		private BGuid m_Guid = BGuid.Empty;
		/// <summary> [Editor Data]Guid </summary>
		public int Guid
		{
			get => m_Guid.GetGuid();
			set
			{
				SetGuid(ref value);
				m_Guid.SetGuid(value,out m_Guid);
			}
		}
		partial void SetGuid(ref int newData);
		private BGuid m_VarGuid_0 = BGuid.Empty;
		/// <summary> [Editor Data]Vector3 </summary>
		public int VarGuid_0
		{
			get => m_VarGuid_0.GetGuid();
			set
			{
				SetVarGuid_0(ref value);
				m_VarGuid_0.SetGuid(value,out m_VarGuid_0);
			}
		}
		/// <summary> Vector3 </summary>
		partial void SetVarGuid_0(ref int newData);
		/// <summary> 获取输入变量长度 </summary>
		public int GetVarGuidsLength()=> 1;
		/// <summary> 设置输入变量Guid </summary>
		public void SetVarsGuid(int index, int value)
		{
			switch(index)
			{
				case 0:
					VarGuid_0 = value;
					break;
			}
		}
		/// <summary> 获取返回值变量Guid </summary>
		public int GetVarGuid(int index)
		{
			switch(index)
			{
				case 0:
					return VarGuid_0;
			}
			return 0;
		}
		/// <summary> 获取变量Guid数组 </summary>
		public int[] GetVarGuids()
		{
			int[] values = new int[1];
			values[0] = VarGuid_0;
			return values;
		}
		private int[] m_Guids = null;
		public int[] GetGuids()
		{
			if (m_Guids == null)
			{
				int guidLen = 2;
				m_Guids = new int[guidLen];
				int index = 0;
				m_Guids[index] = Guid;
				index++;
				m_Guids[index] = VarGuid_0;

			}
			else
			{
				int guidLen = 2;
				if (guidLen != m_Guids.Length)
				{
					m_Guids = new int[guidLen];
				}
				int index = 0;
				m_Guids[index] = Guid;
				index++;
				m_Guids[index] = VarGuid_0;

			}
			return m_Guids;
		}
		public void RefreshGuids(Dictionary<int, int> map)
		{
			if (Guid != ScratchUtils.InvalidGuid && map.ContainsKey(Guid)) Guid = map[Guid];
			if (VarGuid_0 != ScratchUtils.InvalidGuid && map.ContainsKey(VarGuid_0)) VarGuid_0 = map[VarGuid_0];

		}
	}
	public partial class BlockLogic_IfElse : IEngineBlockConditionBase
	{
		/// <summary> [Editor Data]功能类型 </summary>
		public FucType FucType => FucType.Control;
		/// <summary> [Editor Data]逻辑类型 </summary>
		public ScratchBlockType Type => ScratchBlockType.IfElse;
		/// <summary> [Editor Data]UI类型 </summary>
		public BlockType BlockType => BlockType.Condition;
		/// <summary> [Editor Data]是否为画布根 </summary>
		public bool IsRoot { get; set; } = false;
		/// <summary> [Editor Data]画布位置(需判断画布根时有效) </summary>
		public BVector2 CanvasPos { get; set; } = BVector2.zero;
		private bool m_Enable = true;
		/// <summary> [Editor Data]编辑器逻辑是否Enable </summary>
		public bool Enable
		{
			get => m_Enable;
			set
			{
				SetEnable(ref value);
				m_Enable = value;
			}
		}
		partial void SetEnable(ref bool newData);
		private BGuid m_Guid = BGuid.Empty;
		/// <summary> [Editor Data]Guid </summary>
		public int Guid
		{
			get => m_Guid.GetGuid();
			set
			{
				SetGuid(ref value);
				m_Guid.SetGuid(value,out m_Guid);
			}
		}
		partial void SetGuid(ref int newData);
		private BGuid m_NextGuid = BGuid.Empty;
		/// <summary> [Editor Data]NextGuid </summary>
		public int NextGuid
		{
			get => m_NextGuid.GetGuid();
			set
			{
				SetNextGuid(ref value);
				m_NextGuid.SetGuid(value,out m_NextGuid);
			}
		}
		partial void SetNextGuid(ref int newData);
		public BGuidList BranchOperationBGuids { get; set; } = BGuidList.CreateEmptyGuidList(1);
		public BGuidList BranchBlockBGuids { get; set; } = BGuidList.CreateEmptyGuidList(2);
		private int[] m_Guids = null;
		public int[] GetGuids()
		{
			if (m_Guids == null)
			{
				int guidLen = 2 + BranchOperationBGuids.Length + BranchBlockBGuids.Length;
				m_Guids = new int[guidLen];
				int index = 0;
				m_Guids[index] = Guid;
				index++;
				m_Guids[index] = NextGuid;
				index++;
				for (int i = 0; i < BranchOperationBGuids.Length; i++)
				{
					m_Guids[i + index] = BranchOperationBGuids[i];
				}
				index += BranchOperationBGuids.Length;
				for (int i = 0; i < BranchBlockBGuids.Length; i++)
				{
					m_Guids[i + index] = BranchBlockBGuids[i];
				}

			}
			else
			{
				int guidLen = 2 + BranchOperationBGuids.Length + BranchBlockBGuids.Length;
				if (guidLen != m_Guids.Length)
				{
					m_Guids = new int[guidLen];
				}
				int index = 0;
				m_Guids[index] = Guid;
				index++;
				m_Guids[index] = NextGuid;
				index++;
				for (int i = 0; i < BranchOperationBGuids.Length; i++)
				{
					m_Guids[i + index] = BranchOperationBGuids[i];
				}
				index += BranchOperationBGuids.Length;
				for (int i = 0; i < BranchBlockBGuids.Length; i++)
				{
					m_Guids[i + index] = BranchBlockBGuids[i];
				}

			}
			return m_Guids;
		}
		public void RefreshGuids(Dictionary<int, int> map)
		{
			if (Guid != ScratchUtils.InvalidGuid && map.ContainsKey(Guid)) Guid = map[Guid];
			if (NextGuid != ScratchUtils.InvalidGuid && map.ContainsKey(NextGuid)) NextGuid = map[NextGuid];
			for (int i = 0; i < BranchOperationBGuids.Length; i++)
			{
				if (BranchOperationBGuids[i] != ScratchUtils.InvalidGuid && map.ContainsKey(BranchOperationBGuids[i])) BranchOperationBGuids[i] = map[BranchOperationBGuids[i]];
			}
			for (int i = 0; i < BranchBlockBGuids.Length; i++)
			{
				if (BranchBlockBGuids[i] != ScratchUtils.InvalidGuid && map.ContainsKey(BranchBlockBGuids[i])) BranchBlockBGuids[i] = map[BranchBlockBGuids[i]];
			}

		}
	}
	public partial class BlockLogic_IntegerValue : IEngineBlockVariableBase
	{
		/// <summary> [Editor Data]功能类型 </summary>
		public FucType FucType => FucType.Variable;
		/// <summary> [Editor Data]逻辑类型 </summary>
		public ScratchBlockType Type => ScratchBlockType.IntegerValue;
		/// <summary> [Editor Data]UI类型 </summary>
		public BlockType BlockType => BlockType.Operation;
		private bool m_Enable = true;
		/// <summary> [Editor Data]编辑器逻辑是否Enable </summary>
		public bool Enable
		{
			get => m_Enable;
			set
			{
				SetEnable(ref value);
				m_Enable = value;
			}
		}
		partial void SetEnable(ref bool newData);
		private BGuid m_Guid = BGuid.Empty;
		/// <summary> [Editor Data]Guid </summary>
		public int Guid
		{
			get => m_Guid.GetGuid();
			set
			{
				SetGuid(ref value);
				m_Guid.SetGuid(value,out m_Guid);
			}
		}
		partial void SetGuid(ref int newData);
		private ScratchFramework.ScratchValueType m_ValueType = ScratchValueType.Integer;
		public ScratchFramework.ScratchValueType ValueType
		{
			get => m_ValueType;
		}
		partial void SetValueType(ref ScratchFramework.ScratchValueType newData);
		private System.String m_VariableName = null;
		public System.String VariableName
		{
			get => m_VariableName;
			set
			{
				SetVariableName(ref value);
				m_VariableName = value;
			}
		}
		partial void SetVariableName(ref System.String newData);
		private System.Object m_VariableValue = null;
		public System.Object VariableValue
		{
			get => m_VariableValue;
			set
			{
				SetVariableValue(ref value);
				m_VariableValue = value;
			}
		}
		partial void SetVariableValue(ref System.Object newData);
		private BGuid m_ReturnParentGuid = BGuid.Empty;
		/// <summary> [Editor Data]NextGuid </summary>
		public int ReturnParentGuid
		{
			get => m_ReturnParentGuid.GetGuid();
			set
			{
				SetReturnParentGuid(ref value);
				m_ReturnParentGuid.SetGuid(value,out m_ReturnParentGuid);
			}
		}
		partial void SetReturnParentGuid(ref System.Int32 newData);
		private int[] m_Guids = null;
		public int[] GetGuids()
		{
			if (m_Guids == null)
			{
				int guidLen = 2;
				m_Guids = new int[guidLen];
				int index = 0;
				m_Guids[index] = Guid;
				index++;
				m_Guids[index] = ReturnParentGuid;

			}
			else
			{
				int guidLen = 2;
				if (guidLen != m_Guids.Length)
				{
					m_Guids = new int[guidLen];
				}
				int index = 0;
				m_Guids[index] = Guid;
				index++;
				m_Guids[index] = ReturnParentGuid;

			}
			return m_Guids;
		}
		public void RefreshGuids(Dictionary<int, int> map)
		{
			if (Guid != ScratchUtils.InvalidGuid && map.ContainsKey(Guid)) Guid = map[Guid];
			if (ReturnParentGuid != ScratchUtils.InvalidGuid && map.ContainsKey(ReturnParentGuid)) ReturnParentGuid = map[ReturnParentGuid];

		}
	}
	public partial class BlockLogic_OnCollisionEnter : IEngineBlockTriggerBase
	{
		/// <summary> [Editor Data]功能类型 </summary>
		public FucType FucType => FucType.Event;
		/// <summary> [Editor Data]逻辑类型 </summary>
		public ScratchBlockType Type => ScratchBlockType.OnCollisionEnter;
		/// <summary> [Editor Data]UI类型 </summary>
		public BlockType BlockType => BlockType.Trigger;
		/// <summary> [Editor Data]是否为画布根 </summary>
		public bool IsRoot { get; set; } = false;
		/// <summary> [Editor Data]画布位置(需判断画布根时有效) </summary>
		public BVector2 CanvasPos { get; set; } = BVector2.zero;
		private bool m_Enable = true;
		/// <summary> [Editor Data]编辑器逻辑是否Enable </summary>
		public bool Enable
		{
			get => m_Enable;
			set
			{
				SetEnable(ref value);
				m_Enable = value;
			}
		}
		partial void SetEnable(ref bool newData);
		private BGuid m_Guid = BGuid.Empty;
		/// <summary> [Editor Data]Guid </summary>
		public int Guid
		{
			get => m_Guid.GetGuid();
			set
			{
				SetGuid(ref value);
				m_Guid.SetGuid(value,out m_Guid);
			}
		}
		partial void SetGuid(ref int newData);
		private BGuid m_NextGuid = BGuid.Empty;
		/// <summary> [Editor Data]NextGuid </summary>
		public int NextGuid
		{
			get => m_NextGuid.GetGuid();
			set
			{
				SetNextGuid(ref value);
				m_NextGuid.SetGuid(value,out m_NextGuid);
			}
		}
		partial void SetNextGuid(ref int newData);
		private BGuid m_ReturnVarGuid_0 = BGuid.Empty;
		/// <summary> [Editor Data][EntityRef, collision target] </summary>
		public int ReturnVarGuid_0
		{
			get => m_ReturnVarGuid_0.GetGuid();
			set
			{
				SetReturnVarGuid_0(ref value);
				m_ReturnVarGuid_0.SetGuid(value,out m_ReturnVarGuid_0);
			}
		}
		/// <summary> [EntityRef, collision target] </summary>
		partial void SetReturnVarGuid_0(ref int newData);
		private BGuid m_ReturnVarGuid_1 = BGuid.Empty;
		/// <summary> [Editor Data][EntityRef, collider] </summary>
		public int ReturnVarGuid_1
		{
			get => m_ReturnVarGuid_1.GetGuid();
			set
			{
				SetReturnVarGuid_1(ref value);
				m_ReturnVarGuid_1.SetGuid(value,out m_ReturnVarGuid_1);
			}
		}
		/// <summary> [EntityRef, collider] </summary>
		partial void SetReturnVarGuid_1(ref int newData);
		/// <summary> 获取返回值变量长度 </summary>
		public int GetReturnValuesLength()=> 2;
		/// <summary> 设置返回值变量Guid </summary>
		public void SetReturnValueGuid(int index, int value)
		{
			switch(index)
			{
				case 0:
					ReturnVarGuid_0 = value;
					break;
				case 1:
					ReturnVarGuid_1 = value;
					break;
			}
		}
		/// <summary> 获取返回值变量Guid </summary>
		public int GetReturnValueGuid(int index)
		{
			switch(index)
			{
				case 0:
					return ReturnVarGuid_0;
				case 1:
					return ReturnVarGuid_1;
			}
			return 0;
		}
		/// <summary> 获取返回值变量Guid数组 </summary>
		public int[] GetReturnValues()
		{
			int[] values = new int[2];
			values[0] = ReturnVarGuid_0;
			values[1] = ReturnVarGuid_1;
			return values;
		}
		private int[] m_Guids = null;
		public int[] GetGuids()
		{
			if (m_Guids == null)
			{
				int guidLen = 4;
				m_Guids = new int[guidLen];
				int index = 0;
				m_Guids[index] = Guid;
				index++;
				m_Guids[index] = NextGuid;
				index++;
				m_Guids[index] = ReturnVarGuid_0;
				index++;
				m_Guids[index] = ReturnVarGuid_1;

			}
			else
			{
				int guidLen = 4;
				if (guidLen != m_Guids.Length)
				{
					m_Guids = new int[guidLen];
				}
				int index = 0;
				m_Guids[index] = Guid;
				index++;
				m_Guids[index] = NextGuid;
				index++;
				m_Guids[index] = ReturnVarGuid_0;
				index++;
				m_Guids[index] = ReturnVarGuid_1;

			}
			return m_Guids;
		}
		public void RefreshGuids(Dictionary<int, int> map)
		{
			if (Guid != ScratchUtils.InvalidGuid && map.ContainsKey(Guid)) Guid = map[Guid];
			if (NextGuid != ScratchUtils.InvalidGuid && map.ContainsKey(NextGuid)) NextGuid = map[NextGuid];
			if (ReturnVarGuid_0 != ScratchUtils.InvalidGuid && map.ContainsKey(ReturnVarGuid_0)) ReturnVarGuid_0 = map[ReturnVarGuid_0];
			if (ReturnVarGuid_1 != ScratchUtils.InvalidGuid && map.ContainsKey(ReturnVarGuid_1)) ReturnVarGuid_1 = map[ReturnVarGuid_1];

		}
	}
	public partial class BlockLogic_OnCollisionExit : IEngineBlockTriggerBase
	{
		/// <summary> [Editor Data]功能类型 </summary>
		public FucType FucType => FucType.Event;
		/// <summary> [Editor Data]逻辑类型 </summary>
		public ScratchBlockType Type => ScratchBlockType.OnCollisionExit;
		/// <summary> [Editor Data]UI类型 </summary>
		public BlockType BlockType => BlockType.Trigger;
		/// <summary> [Editor Data]是否为画布根 </summary>
		public bool IsRoot { get; set; } = false;
		/// <summary> [Editor Data]画布位置(需判断画布根时有效) </summary>
		public BVector2 CanvasPos { get; set; } = BVector2.zero;
		private bool m_Enable = true;
		/// <summary> [Editor Data]编辑器逻辑是否Enable </summary>
		public bool Enable
		{
			get => m_Enable;
			set
			{
				SetEnable(ref value);
				m_Enable = value;
			}
		}
		partial void SetEnable(ref bool newData);
		private BGuid m_Guid = BGuid.Empty;
		/// <summary> [Editor Data]Guid </summary>
		public int Guid
		{
			get => m_Guid.GetGuid();
			set
			{
				SetGuid(ref value);
				m_Guid.SetGuid(value,out m_Guid);
			}
		}
		partial void SetGuid(ref int newData);
		private BGuid m_NextGuid = BGuid.Empty;
		/// <summary> [Editor Data]NextGuid </summary>
		public int NextGuid
		{
			get => m_NextGuid.GetGuid();
			set
			{
				SetNextGuid(ref value);
				m_NextGuid.SetGuid(value,out m_NextGuid);
			}
		}
		partial void SetNextGuid(ref int newData);
		private BGuid m_ReturnVarGuid_0 = BGuid.Empty;
		/// <summary> [Editor Data][EntityRef, collision target] </summary>
		public int ReturnVarGuid_0
		{
			get => m_ReturnVarGuid_0.GetGuid();
			set
			{
				SetReturnVarGuid_0(ref value);
				m_ReturnVarGuid_0.SetGuid(value,out m_ReturnVarGuid_0);
			}
		}
		/// <summary> [EntityRef, collision target] </summary>
		partial void SetReturnVarGuid_0(ref int newData);
		private BGuid m_ReturnVarGuid_1 = BGuid.Empty;
		/// <summary> [Editor Data][EntityRef, collider] </summary>
		public int ReturnVarGuid_1
		{
			get => m_ReturnVarGuid_1.GetGuid();
			set
			{
				SetReturnVarGuid_1(ref value);
				m_ReturnVarGuid_1.SetGuid(value,out m_ReturnVarGuid_1);
			}
		}
		/// <summary> [EntityRef, collider] </summary>
		partial void SetReturnVarGuid_1(ref int newData);
		/// <summary> 获取返回值变量长度 </summary>
		public int GetReturnValuesLength()=> 2;
		/// <summary> 设置返回值变量Guid </summary>
		public void SetReturnValueGuid(int index, int value)
		{
			switch(index)
			{
				case 0:
					ReturnVarGuid_0 = value;
					break;
				case 1:
					ReturnVarGuid_1 = value;
					break;
			}
		}
		/// <summary> 获取返回值变量Guid </summary>
		public int GetReturnValueGuid(int index)
		{
			switch(index)
			{
				case 0:
					return ReturnVarGuid_0;
				case 1:
					return ReturnVarGuid_1;
			}
			return 0;
		}
		/// <summary> 获取返回值变量Guid数组 </summary>
		public int[] GetReturnValues()
		{
			int[] values = new int[2];
			values[0] = ReturnVarGuid_0;
			values[1] = ReturnVarGuid_1;
			return values;
		}
		private int[] m_Guids = null;
		public int[] GetGuids()
		{
			if (m_Guids == null)
			{
				int guidLen = 4;
				m_Guids = new int[guidLen];
				int index = 0;
				m_Guids[index] = Guid;
				index++;
				m_Guids[index] = NextGuid;
				index++;
				m_Guids[index] = ReturnVarGuid_0;
				index++;
				m_Guids[index] = ReturnVarGuid_1;

			}
			else
			{
				int guidLen = 4;
				if (guidLen != m_Guids.Length)
				{
					m_Guids = new int[guidLen];
				}
				int index = 0;
				m_Guids[index] = Guid;
				index++;
				m_Guids[index] = NextGuid;
				index++;
				m_Guids[index] = ReturnVarGuid_0;
				index++;
				m_Guids[index] = ReturnVarGuid_1;

			}
			return m_Guids;
		}
		public void RefreshGuids(Dictionary<int, int> map)
		{
			if (Guid != ScratchUtils.InvalidGuid && map.ContainsKey(Guid)) Guid = map[Guid];
			if (NextGuid != ScratchUtils.InvalidGuid && map.ContainsKey(NextGuid)) NextGuid = map[NextGuid];
			if (ReturnVarGuid_0 != ScratchUtils.InvalidGuid && map.ContainsKey(ReturnVarGuid_0)) ReturnVarGuid_0 = map[ReturnVarGuid_0];
			if (ReturnVarGuid_1 != ScratchUtils.InvalidGuid && map.ContainsKey(ReturnVarGuid_1)) ReturnVarGuid_1 = map[ReturnVarGuid_1];

		}
	}
	public partial class BlockLogic_OnCollisionStay : IEngineBlockTriggerBase
	{
		/// <summary> [Editor Data]功能类型 </summary>
		public FucType FucType => FucType.Event;
		/// <summary> [Editor Data]逻辑类型 </summary>
		public ScratchBlockType Type => ScratchBlockType.OnCollisionStay;
		/// <summary> [Editor Data]UI类型 </summary>
		public BlockType BlockType => BlockType.Trigger;
		/// <summary> [Editor Data]是否为画布根 </summary>
		public bool IsRoot { get; set; } = false;
		/// <summary> [Editor Data]画布位置(需判断画布根时有效) </summary>
		public BVector2 CanvasPos { get; set; } = BVector2.zero;
		private bool m_Enable = true;
		/// <summary> [Editor Data]编辑器逻辑是否Enable </summary>
		public bool Enable
		{
			get => m_Enable;
			set
			{
				SetEnable(ref value);
				m_Enable = value;
			}
		}
		partial void SetEnable(ref bool newData);
		private BGuid m_Guid = BGuid.Empty;
		/// <summary> [Editor Data]Guid </summary>
		public int Guid
		{
			get => m_Guid.GetGuid();
			set
			{
				SetGuid(ref value);
				m_Guid.SetGuid(value,out m_Guid);
			}
		}
		partial void SetGuid(ref int newData);
		private BGuid m_NextGuid = BGuid.Empty;
		/// <summary> [Editor Data]NextGuid </summary>
		public int NextGuid
		{
			get => m_NextGuid.GetGuid();
			set
			{
				SetNextGuid(ref value);
				m_NextGuid.SetGuid(value,out m_NextGuid);
			}
		}
		partial void SetNextGuid(ref int newData);
		private BGuid m_ReturnVarGuid_0 = BGuid.Empty;
		/// <summary> [Editor Data][EntityRef, collision target] </summary>
		public int ReturnVarGuid_0
		{
			get => m_ReturnVarGuid_0.GetGuid();
			set
			{
				SetReturnVarGuid_0(ref value);
				m_ReturnVarGuid_0.SetGuid(value,out m_ReturnVarGuid_0);
			}
		}
		/// <summary> [EntityRef, collision target] </summary>
		partial void SetReturnVarGuid_0(ref int newData);
		private BGuid m_ReturnVarGuid_1 = BGuid.Empty;
		/// <summary> [Editor Data][EntityRef, collider] </summary>
		public int ReturnVarGuid_1
		{
			get => m_ReturnVarGuid_1.GetGuid();
			set
			{
				SetReturnVarGuid_1(ref value);
				m_ReturnVarGuid_1.SetGuid(value,out m_ReturnVarGuid_1);
			}
		}
		/// <summary> [EntityRef, collider] </summary>
		partial void SetReturnVarGuid_1(ref int newData);
		/// <summary> 获取返回值变量长度 </summary>
		public int GetReturnValuesLength()=> 2;
		/// <summary> 设置返回值变量Guid </summary>
		public void SetReturnValueGuid(int index, int value)
		{
			switch(index)
			{
				case 0:
					ReturnVarGuid_0 = value;
					break;
				case 1:
					ReturnVarGuid_1 = value;
					break;
			}
		}
		/// <summary> 获取返回值变量Guid </summary>
		public int GetReturnValueGuid(int index)
		{
			switch(index)
			{
				case 0:
					return ReturnVarGuid_0;
				case 1:
					return ReturnVarGuid_1;
			}
			return 0;
		}
		/// <summary> 获取返回值变量Guid数组 </summary>
		public int[] GetReturnValues()
		{
			int[] values = new int[2];
			values[0] = ReturnVarGuid_0;
			values[1] = ReturnVarGuid_1;
			return values;
		}
		private int[] m_Guids = null;
		public int[] GetGuids()
		{
			if (m_Guids == null)
			{
				int guidLen = 4;
				m_Guids = new int[guidLen];
				int index = 0;
				m_Guids[index] = Guid;
				index++;
				m_Guids[index] = NextGuid;
				index++;
				m_Guids[index] = ReturnVarGuid_0;
				index++;
				m_Guids[index] = ReturnVarGuid_1;

			}
			else
			{
				int guidLen = 4;
				if (guidLen != m_Guids.Length)
				{
					m_Guids = new int[guidLen];
				}
				int index = 0;
				m_Guids[index] = Guid;
				index++;
				m_Guids[index] = NextGuid;
				index++;
				m_Guids[index] = ReturnVarGuid_0;
				index++;
				m_Guids[index] = ReturnVarGuid_1;

			}
			return m_Guids;
		}
		public void RefreshGuids(Dictionary<int, int> map)
		{
			if (Guid != ScratchUtils.InvalidGuid && map.ContainsKey(Guid)) Guid = map[Guid];
			if (NextGuid != ScratchUtils.InvalidGuid && map.ContainsKey(NextGuid)) NextGuid = map[NextGuid];
			if (ReturnVarGuid_0 != ScratchUtils.InvalidGuid && map.ContainsKey(ReturnVarGuid_0)) ReturnVarGuid_0 = map[ReturnVarGuid_0];
			if (ReturnVarGuid_1 != ScratchUtils.InvalidGuid && map.ContainsKey(ReturnVarGuid_1)) ReturnVarGuid_1 = map[ReturnVarGuid_1];

		}
	}
	public partial class BlockLogic_OnObjectCreated : IEngineBlockTriggerBase
	{
		/// <summary> [Editor Data]功能类型 </summary>
		public FucType FucType => FucType.Event;
		/// <summary> [Editor Data]逻辑类型 </summary>
		public ScratchBlockType Type => ScratchBlockType.OnObjectCreated;
		/// <summary> [Editor Data]UI类型 </summary>
		public BlockType BlockType => BlockType.Trigger;
		/// <summary> [Editor Data]是否为画布根 </summary>
		public bool IsRoot { get; set; } = false;
		/// <summary> [Editor Data]画布位置(需判断画布根时有效) </summary>
		public BVector2 CanvasPos { get; set; } = BVector2.zero;
		private bool m_Enable = true;
		/// <summary> [Editor Data]编辑器逻辑是否Enable </summary>
		public bool Enable
		{
			get => m_Enable;
			set
			{
				SetEnable(ref value);
				m_Enable = value;
			}
		}
		partial void SetEnable(ref bool newData);
		private BGuid m_Guid = BGuid.Empty;
		/// <summary> [Editor Data]Guid </summary>
		public int Guid
		{
			get => m_Guid.GetGuid();
			set
			{
				SetGuid(ref value);
				m_Guid.SetGuid(value,out m_Guid);
			}
		}
		partial void SetGuid(ref int newData);
		private BGuid m_NextGuid = BGuid.Empty;
		/// <summary> [Editor Data]NextGuid </summary>
		public int NextGuid
		{
			get => m_NextGuid.GetGuid();
			set
			{
				SetNextGuid(ref value);
				m_NextGuid.SetGuid(value,out m_NextGuid);
			}
		}
		partial void SetNextGuid(ref int newData);
		/// <summary> 获取返回值变量长度 </summary>
		public int GetReturnValuesLength()=> 0;
		/// <summary> 设置返回值变量Guid </summary>
		public void SetReturnValueGuid(int index, int value)
		{
		}
		/// <summary> 获取返回值变量Guid </summary>
		public int GetReturnValueGuid(int index)
		{
			return 0;
		}
		/// <summary> 获取返回值变量Guid数组 </summary>
		public int[] GetReturnValues()
		{
			int[] values = new int[0];
			return values;
		}
		private int[] m_Guids = null;
		public int[] GetGuids()
		{
			if (m_Guids == null)
			{
				int guidLen = 2;
				m_Guids = new int[guidLen];
				int index = 0;
				m_Guids[index] = Guid;
				index++;
				m_Guids[index] = NextGuid;

			}
			else
			{
				int guidLen = 2;
				if (guidLen != m_Guids.Length)
				{
					m_Guids = new int[guidLen];
				}
				int index = 0;
				m_Guids[index] = Guid;
				index++;
				m_Guids[index] = NextGuid;

			}
			return m_Guids;
		}
		public void RefreshGuids(Dictionary<int, int> map)
		{
			if (Guid != ScratchUtils.InvalidGuid && map.ContainsKey(Guid)) Guid = map[Guid];
			if (NextGuid != ScratchUtils.InvalidGuid && map.ContainsKey(NextGuid)) NextGuid = map[NextGuid];

		}
	}
	public partial class BlockLogic_RepeatAction : IEngineBlockLoopBase
	{
		/// <summary> [Editor Data]功能类型 </summary>
		public FucType FucType => FucType.Control;
		/// <summary> [Editor Data]逻辑类型 </summary>
		public ScratchBlockType Type => ScratchBlockType.RepeatAction;
		/// <summary> [Editor Data]UI类型 </summary>
		public BlockType BlockType => BlockType.Loop;
		/// <summary> [Editor Data]是否为画布根 </summary>
		public bool IsRoot { get; set; } = false;
		/// <summary> [Editor Data]画布位置(需判断画布根时有效) </summary>
		public BVector2 CanvasPos { get; set; } = BVector2.zero;
		private bool m_Enable = true;
		/// <summary> [Editor Data]编辑器逻辑是否Enable </summary>
		public bool Enable
		{
			get => m_Enable;
			set
			{
				SetEnable(ref value);
				m_Enable = value;
			}
		}
		partial void SetEnable(ref bool newData);
		private BGuid m_Guid = BGuid.Empty;
		/// <summary> [Editor Data]Guid </summary>
		public int Guid
		{
			get => m_Guid.GetGuid();
			set
			{
				SetGuid(ref value);
				m_Guid.SetGuid(value,out m_Guid);
			}
		}
		partial void SetGuid(ref int newData);
		private BGuid m_NextGuid = BGuid.Empty;
		/// <summary> [Editor Data]NextGuid </summary>
		public int NextGuid
		{
			get => m_NextGuid.GetGuid();
			set
			{
				SetNextGuid(ref value);
				m_NextGuid.SetGuid(value,out m_NextGuid);
			}
		}
		partial void SetNextGuid(ref int newData);
		private BGuid m_ChildRootGuid = BGuid.Empty;
		/// <summary> [Editor Data]NextGuid </summary>
		public int ChildRootGuid
		{
			get => m_ChildRootGuid.GetGuid();
			set
			{
				SetChildRootGuid(ref value);
				m_ChildRootGuid.SetGuid(value,out m_ChildRootGuid);
			}
		}
		partial void SetChildRootGuid(ref System.Int32 newData);
		private BGuid m_VarGuid_0 = BGuid.Empty;
		/// <summary> [Editor Data]integer </summary>
		public int VarGuid_0
		{
			get => m_VarGuid_0.GetGuid();
			set
			{
				SetVarGuid_0(ref value);
				m_VarGuid_0.SetGuid(value,out m_VarGuid_0);
			}
		}
		/// <summary> integer </summary>
		partial void SetVarGuid_0(ref int newData);
		/// <summary> 获取输入变量长度 </summary>
		public int GetVarGuidsLength()=> 1;
		/// <summary> 设置输入变量Guid </summary>
		public void SetVarsGuid(int index, int value)
		{
			switch(index)
			{
				case 0:
					VarGuid_0 = value;
					break;
			}
		}
		/// <summary> 获取返回值变量Guid </summary>
		public int GetVarGuid(int index)
		{
			switch(index)
			{
				case 0:
					return VarGuid_0;
			}
			return 0;
		}
		/// <summary> 获取变量Guid数组 </summary>
		public int[] GetVarGuids()
		{
			int[] values = new int[1];
			values[0] = VarGuid_0;
			return values;
		}
		private int[] m_Guids = null;
		public int[] GetGuids()
		{
			if (m_Guids == null)
			{
				int guidLen = 3;
				m_Guids = new int[guidLen];
				int index = 0;
				m_Guids[index] = Guid;
				index++;
				m_Guids[index] = NextGuid;
				index++;
				m_Guids[index] = VarGuid_0;

			}
			else
			{
				int guidLen = 3;
				if (guidLen != m_Guids.Length)
				{
					m_Guids = new int[guidLen];
				}
				int index = 0;
				m_Guids[index] = Guid;
				index++;
				m_Guids[index] = NextGuid;
				index++;
				m_Guids[index] = VarGuid_0;

			}
			return m_Guids;
		}
		public void RefreshGuids(Dictionary<int, int> map)
		{
			if (Guid != ScratchUtils.InvalidGuid && map.ContainsKey(Guid)) Guid = map[Guid];
			if (NextGuid != ScratchUtils.InvalidGuid && map.ContainsKey(NextGuid)) NextGuid = map[NextGuid];
			if (VarGuid_0 != ScratchUtils.InvalidGuid && map.ContainsKey(VarGuid_0)) VarGuid_0 = map[VarGuid_0];

		}
	}
	public partial class BlockLogic_StartCountdown : IEngineBlockLoopBase
	{
		/// <summary> [Editor Data]功能类型 </summary>
		public FucType FucType => FucType.Control;
		/// <summary> [Editor Data]逻辑类型 </summary>
		public ScratchBlockType Type => ScratchBlockType.StartCountdown;
		/// <summary> [Editor Data]UI类型 </summary>
		public BlockType BlockType => BlockType.Loop;
		/// <summary> [Editor Data]是否为画布根 </summary>
		public bool IsRoot { get; set; } = false;
		/// <summary> [Editor Data]画布位置(需判断画布根时有效) </summary>
		public BVector2 CanvasPos { get; set; } = BVector2.zero;
		private bool m_Enable = true;
		/// <summary> [Editor Data]编辑器逻辑是否Enable </summary>
		public bool Enable
		{
			get => m_Enable;
			set
			{
				SetEnable(ref value);
				m_Enable = value;
			}
		}
		partial void SetEnable(ref bool newData);
		private BGuid m_Guid = BGuid.Empty;
		/// <summary> [Editor Data]Guid </summary>
		public int Guid
		{
			get => m_Guid.GetGuid();
			set
			{
				SetGuid(ref value);
				m_Guid.SetGuid(value,out m_Guid);
			}
		}
		partial void SetGuid(ref int newData);
		private BGuid m_NextGuid = BGuid.Empty;
		/// <summary> [Editor Data]NextGuid </summary>
		public int NextGuid
		{
			get => m_NextGuid.GetGuid();
			set
			{
				SetNextGuid(ref value);
				m_NextGuid.SetGuid(value,out m_NextGuid);
			}
		}
		partial void SetNextGuid(ref int newData);
		private BGuid m_ChildRootGuid = BGuid.Empty;
		/// <summary> [Editor Data]NextGuid </summary>
		public int ChildRootGuid
		{
			get => m_ChildRootGuid.GetGuid();
			set
			{
				SetChildRootGuid(ref value);
				m_ChildRootGuid.SetGuid(value,out m_ChildRootGuid);
			}
		}
		partial void SetChildRootGuid(ref System.Int32 newData);
		private BGuid m_VarGuid_0 = BGuid.Empty;
		/// <summary> [Editor Data]integer </summary>
		public int VarGuid_0
		{
			get => m_VarGuid_0.GetGuid();
			set
			{
				SetVarGuid_0(ref value);
				m_VarGuid_0.SetGuid(value,out m_VarGuid_0);
			}
		}
		/// <summary> integer </summary>
		partial void SetVarGuid_0(ref int newData);
		/// <summary> 获取输入变量长度 </summary>
		public int GetVarGuidsLength()=> 1;
		/// <summary> 设置输入变量Guid </summary>
		public void SetVarsGuid(int index, int value)
		{
			switch(index)
			{
				case 0:
					VarGuid_0 = value;
					break;
			}
		}
		/// <summary> 获取返回值变量Guid </summary>
		public int GetVarGuid(int index)
		{
			switch(index)
			{
				case 0:
					return VarGuid_0;
			}
			return 0;
		}
		/// <summary> 获取变量Guid数组 </summary>
		public int[] GetVarGuids()
		{
			int[] values = new int[1];
			values[0] = VarGuid_0;
			return values;
		}
		private int[] m_Guids = null;
		public int[] GetGuids()
		{
			if (m_Guids == null)
			{
				int guidLen = 3;
				m_Guids = new int[guidLen];
				int index = 0;
				m_Guids[index] = Guid;
				index++;
				m_Guids[index] = NextGuid;
				index++;
				m_Guids[index] = VarGuid_0;

			}
			else
			{
				int guidLen = 3;
				if (guidLen != m_Guids.Length)
				{
					m_Guids = new int[guidLen];
				}
				int index = 0;
				m_Guids[index] = Guid;
				index++;
				m_Guids[index] = NextGuid;
				index++;
				m_Guids[index] = VarGuid_0;

			}
			return m_Guids;
		}
		public void RefreshGuids(Dictionary<int, int> map)
		{
			if (Guid != ScratchUtils.InvalidGuid && map.ContainsKey(Guid)) Guid = map[Guid];
			if (NextGuid != ScratchUtils.InvalidGuid && map.ContainsKey(NextGuid)) NextGuid = map[NextGuid];
			if (VarGuid_0 != ScratchUtils.InvalidGuid && map.ContainsKey(VarGuid_0)) VarGuid_0 = map[VarGuid_0];

		}
	}
	public partial class BlockLogic_VectorValue : IEngineBlockVariableBase
	{
		/// <summary> [Editor Data]功能类型 </summary>
		public FucType FucType => FucType.Variable;
		/// <summary> [Editor Data]逻辑类型 </summary>
		public ScratchBlockType Type => ScratchBlockType.VectorValue;
		/// <summary> [Editor Data]UI类型 </summary>
		public BlockType BlockType => BlockType.Operation;
		private bool m_Enable = true;
		/// <summary> [Editor Data]编辑器逻辑是否Enable </summary>
		public bool Enable
		{
			get => m_Enable;
			set
			{
				SetEnable(ref value);
				m_Enable = value;
			}
		}
		partial void SetEnable(ref bool newData);
		private BGuid m_Guid = BGuid.Empty;
		/// <summary> [Editor Data]Guid </summary>
		public int Guid
		{
			get => m_Guid.GetGuid();
			set
			{
				SetGuid(ref value);
				m_Guid.SetGuid(value,out m_Guid);
			}
		}
		partial void SetGuid(ref int newData);
		private ScratchFramework.ScratchValueType m_ValueType = ScratchValueType.Vector3;
		public ScratchFramework.ScratchValueType ValueType
		{
			get => m_ValueType;
		}
		partial void SetValueType(ref ScratchFramework.ScratchValueType newData);
		private System.String m_VariableName = null;
		public System.String VariableName
		{
			get => m_VariableName;
			set
			{
				SetVariableName(ref value);
				m_VariableName = value;
			}
		}
		partial void SetVariableName(ref System.String newData);
		private System.Object m_VariableValue = null;
		public System.Object VariableValue
		{
			get => m_VariableValue;
			set
			{
				SetVariableValue(ref value);
				m_VariableValue = value;
			}
		}
		partial void SetVariableValue(ref System.Object newData);
		private BGuid m_ReturnParentGuid = BGuid.Empty;
		/// <summary> [Editor Data]NextGuid </summary>
		public int ReturnParentGuid
		{
			get => m_ReturnParentGuid.GetGuid();
			set
			{
				SetReturnParentGuid(ref value);
				m_ReturnParentGuid.SetGuid(value,out m_ReturnParentGuid);
			}
		}
		partial void SetReturnParentGuid(ref System.Int32 newData);
		private int[] m_Guids = null;
		public int[] GetGuids()
		{
			if (m_Guids == null)
			{
				int guidLen = 2;
				m_Guids = new int[guidLen];
				int index = 0;
				m_Guids[index] = Guid;
				index++;
				m_Guids[index] = ReturnParentGuid;

			}
			else
			{
				int guidLen = 2;
				if (guidLen != m_Guids.Length)
				{
					m_Guids = new int[guidLen];
				}
				int index = 0;
				m_Guids[index] = Guid;
				index++;
				m_Guids[index] = ReturnParentGuid;

			}
			return m_Guids;
		}
		public void RefreshGuids(Dictionary<int, int> map)
		{
			if (Guid != ScratchUtils.InvalidGuid && map.ContainsKey(Guid)) Guid = map[Guid];
			if (ReturnParentGuid != ScratchUtils.InvalidGuid && map.ContainsKey(ReturnParentGuid)) ReturnParentGuid = map[ReturnParentGuid];

		}
	}
}
